# Generated by Django 5.0.6 on 2024-06-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='phone',
            new_name='telefono',
        ),
    ]
