# Generated by Django 3.2.20 on 2024-06-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
